config/routes.rb
PaozhoumoUser::Engine.routes.draw do
  get "admin/userlist", :to => "admin#userlist"
  get "admin/user/:id", :to => "admin#edit", :as => "admin_useredit"
  put "admin/user/:id", :to => "admin#update", :as => "admin_userupdate"
  # get "sessions/create"

  devise_for :users, {
    :path => "user",
    :class_name => "PaozhoumoUser::User",
    :controllers => {
      :registrations => "paozhoumo_user/registrations",
      :omniauth_callbacks => "paozhoumo_user/omniauth_callbacks"
    },
    module: :devise
  }
end

app/models/paozhoumo_user/authorization.rb
module PaozhoumoUser
  class Authorization < ActiveRecord::Base
    belongs_to :user
    attr_accessible :provider, :uid, :user_id
    # validates :provider, :presence => true, :uniqueness => {:scope => :user_id}
    # validates :uid, :presence => true, :uniqueness => {:scope => :provider}
    # belongs_to :admin, :foreign_key=> "user_id"

    # def self.create_with_omniauth(auth)
    #       create! do |authorization|
    #         authorization.provider = auth["provider"]
    #         authorization.uid = auth["uid"]
    #         # authorization.name = auth["user_info"]["name"]
    #       end
    #     end
  end
end

app/models/paozhoumo_user/paozhoumo_user.rb
module PaozhoumoUser
  def self.table_name_prefix
    'paozhoumo_user_'
  end
end

app/models/paozhoumo_user/role.rb
module PaozhoumoUser
  class Role < ActiveRecord::Base
    attr_accessible :name
  end
end

app/models/paozhoumo_user/settings.rb
module PaozhoumoUser
  class Settings < Settingslogic
    source "#{Rails.root}/config/application.yml"
    namespace Rails.env
  end
end

app/models/paozhoumo_user/user.rb
# coding: utf-8
module PaozhoumoUser
  class User < ActiveRecord::Base 
    extend OmniauthCallbacks
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :token_authenticatable, :omniauthable#, :confirmable, :lockable 

    # Setup accessible (or protected) attributes for your model
    attr_accessible :email, :password, :password_confirmation, :remember_me, :role_id
    
    has_many :authorizations
    
    belongs_to :role
    
  end
end

app/models/paozhoumo_user/user/omniauth_callbacks.rb
# coding: utf-8
module PaozhoumoUser
  class User
    module OmniauthCallbacks
      ["weibo"].each do |provider|
        define_method "find_or_create_for_#{provider}" do |response|
          uid = response["uid"]
          data = response["info"]
          if user = User.where("paozhoumo_user_authorizations.provider" => provider , "paozhoumo_user_authorizations.uid" => uid).includes("authorizations").first
            user
          elsif user = User.find_by_email(data["email"])
            user.bind_service(response)
            user
          else
            user = User.new_from_provider_data(provider, uid, data)

            if user.save(:validate => false)
              user.authorizations << Authorization.new(:provider => provider, :uid => uid )
              return user
            else
              Rails.logger.warn("User.create_from_hash 失败，#{user.errors.inspect}")
              return nil
            end
          end
        end
      end

      def new_from_provider_data(provider, uid, data)
        User.new do |user|
          user.email = data["email"]
          user.email = "twitter_#{uid}@twitter.com" if provider == "twitter"
          user.email = "douban_#{uid}@douban.com" if provider == "douban"
          user.email = "weibo_#{uid}@weibo.com" if provider == "weibo"
          user.role_id = 3
          #user.login = data["nickname"]
          #user.login = data["name"] if provider == "google"
          #user.login.gsub!(/[^\w]/, "_")

          #if User.where(:login => user.login).count > 0 || user.login.blank?
            #user.login = "u#{Time.now.to_i}" # TODO: possibly duplicated user login here. What should we do?
          #end

          #user.password = Devise.friendly_token[0, 20]
          #user.location = data["location"]
          #user.tagline = data["description"]
        end
      end
    end
  end
end

app/controllers/paozhoumo-user/application_controller.rb
module PaozhoumoUser
  class ApplicationController < ActionController::Base
  end
end

app/controllers/paozhoumo_user/admin_controller.rb
# coding: utf-8
module PaozhoumoUser
  class AdminController < ApplicationController
    before_filter :authenticate_user!
    
    layout 'devise'
    def userlist
      @users = User.find(:all)
    end
    def edit
      @user = User.find params[:id]
    end
    def update
      @user = User.find params[:id]
      if @user.update_attributes(params[:user])
        redirect_to admin_userlist_path(@user), notice: '更新成功.'
      else
        render action: "edit"
      end
    end
  end
end

app/controllers/paozhoumo_user/omniauth_callbacks_controller.rb
# coding: utf-8
class PaozhoumoUser::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(*providers)
    providers.each do |provider|
      class_eval %Q{
        def #{provider}
          if not current_user.blank?
            current_user.bind_service(env["omniauth.auth"])#Add an auth to existing
            redirect_to edit_user_registration_path, :notice => "成功绑定了 #{provider} 帐号。"
          else
            @user = PaozhoumoUser::User.find_or_create_for_#{provider}(env["omniauth.auth"])
            if @user.persisted?
              flash[:notice] = "Signed in with #{provider.to_s.titleize} successfully."
              sign_in_and_redirect @user, :event => :authentication, :notice => "登陆成功。"
            else
              redirect_to new_user_registration_url
            end
          end
        end
      }
    end
  end

  provides_callback_for :weibo

  # This is solution for existing accout want bind Google login but current_user is always nil
  # https://github.com/intridea/omniauth/issues/185
  def handle_unverified_request
    true
  end


end

app/controllers/paozhoumo_user/registrations_controller.rb
class PaozhoumoUser::RegistrationsController < Devise::RegistrationsController
  
  # POST /resource
  def create
    build_resource
    resource.role_id = 3
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/helpers/paozhoumo-user/application_helper.rb
module PaozhoumoUser
  module ApplicationHelper
  end
end

app/helpers/paozhoumo_user/admin_helper.rb
module PaozhoumoUser
  module AdminHelper
  end
end

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaozhoumoUser</title>
  <%= stylesheet_link_tag    "paozhoumo-user/application" %>
	<%#= stylesheet_link_tag    "paozhoumo-user/bootstrap" %>
  <%= javascript_include_tag "paozhoumo-user/application" %>
  <%#= javascript_include_tag "paozhoumo-user/bootstrap" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: white;">	
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				  <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand">
				  泡周末
				</a>
				<ul class="nav">
				  <li class="active">
				    <a href="#">
				    	主页
				    </a>
				  </li>
				  <li class="divider-vertical"></li>
				  <li><a href="#">热门</a></li>
				  <li><a href="#">帮助</a></li>
				</ul>
				<div class="nav-collapse">
					<form class="navbar-search pull-left">
					  <input type="text" class="search-query" placeholder="搜索">
					</form>
	      </div>
	    </div>
	  </div>
	</div>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/paozhoumo_user/admin/edit.html.erb
<h2>编辑 <%#= resource_name.to_s.humanize %></h2>

<%= form_for(@user, :url => admin_userupdate_path(@user), :html => { :method => :put, :class => "form-horizontal" }) do |f| %>
  <%#= devise_error_messages! %>
	<fieldset>
		<div class="control-group">
  		<label class="control-label" for="input01"><%= f.label :email, "邮箱" %></label>
			<div class="controls"><%= @user.email %></div>
		</div>
		<div class="control-group">
  		<label class="control-label" for="input01"><%= f.label :role_id, "权限" %></label>
			<div class="controls"><%=  f.select(:role_id, PaozhoumoUser::Role.find(:all, :order => 'name').collect{|r| [r.name,r.id]}) %><%#= f.text_field :role_id %></div>
		</div>
		<div class="controls">
			<%#= f.submit "修改" %>
			
			<!--<h3>删除账号</h3>

			<p>不高兴? <%#= link_to "将账号删除", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete %>.</p>-->

			<%#= link_to "返回", :back %>
		</div>	
		<div class="form-actions">
			 <div style="float: left; width: auto;">
			 	<%= button_to "修改", "", :class => "btn btn-primary", :type => "submit" %>
			 </div> 
			 <div style="float: left; width: auto; margin-left:10px">
			 	<%= button_to "返回", :back, :class => "btn" %>
			 </div> 
    </div>
	</fieldset>
<% end %>

app/views/paozhoumo_user/admin/update.html.erb
success!!!

app/views/paozhoumo_user/admin/userlist.html.erb
用户管理
<%= notice %>
<% if can? :update, @user %>  
<table class="table table-bordered">
  <thead>
	    <tr>
	      <th>#</th>
	      <th>用户邮箱</th>
	      <th>登陆次数</th>
	      <th>IP</th>
	      <th>
	      	权限
	      </th>
	      <th>
	      	修改
	      </th>
	    </tr>
	  </thead>
	  <tbody>
			<% @users.each do |user| %>
	    <tr>
	      <td><%= user.id%></td>
	      <td><%= user.email%></td>
	      <td><%= user.sign_in_count%></td>
	      <td><%= user.last_sign_in_ip%></td>
				<td><%= user.role.name%></td>
				<td><a class="btn btn-primary" href="<%= admin_useredit_path(user)%>">
					修改
				</a></td>
	    </tr>	
			<% end %>
	  </tbody>
</table>
<% end %>